name: 'Minha Composite Action em JS'
description: 'Uma nova compostie action'

inputs:
  my-input:
    description: 'Input vindo do workflow'
    required: true
    
outputs:
  my-output:
    description: 'Meu output'

runs:
  using: 'node20'
  main: 'index.js'
  
