name: 'Minha Composite Action'
description: 'Uma nova compostie action'

inputs:
  my-input:
    description: 'Input vindo do workflow'
    required: true
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Hello ${{ inputs.my-input }}
      run: echo "Hello ${{ inputs.my-input }}!"
      shell: bash
