name: 'Minha Composite Action'
description: 'Uma nova compostie action'

inputs:
  my-input:
    description: 'Input vindo do workflow'
    required: true
    default: ''

outputs:
  my-output:
    value: ${{ steps.hello-world-msg.outputs.output }}

runs:
  using: 'composite'
  steps:
    - name: Hello ${{ inputs.my-input }}
      run: echo "Hello ${{ inputs.my-input }}!"
      shell: bash

    - name: Send Output
      id: hello-world-msg
      run: echo "output='Hello ${{ inputs.my-input }}'" >> $GITHUB_OUTPUT
      shell: bash
