name: Deploy Production

on:
  push:
    branches: [ develop ]

jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Deploy Develop Server
      run: echo "Deploying to develop server..."
      shell: bash
