name: Deploy With Expressions

on:
  push:
    branches: [ main, develop ]

jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - if: ${{ github.ref == 'refs/heads/main' }}
      id: deploy-prod
      name: Deploy Production Server
      run: echo "Deploying to production server..."
      shell: bash
    
    - if: ${{ github.ref == 'refs/heads/develop' }}
      id: deploy-develop
      name: Deploy Develop Server
      run: echo "Deploying to develop server..."
      shell: bash
    
    - if: ${{ github.ref == 'refs/heads/main' && steps.deploy-prod.conclusion == 'success' }}
      name: Status Deploy Prod
      run: echo "Deployed to production Server!"
      shell: bash

    - if: ${{ github.ref == 'refs/heads/develop' && steps.deploy-develop.conclusion == 'success' }}
      name: Status Deploy Develop
      run: echo "Deployed to develop Server!"
      shell: bash


  
  post-deploy:
    runs-on: ubuntu-latest
    needs: deploy
    if: ${{ success() }}
    steps:
      - uses: actions/checkout@v4
      - name: Celaning Server Artifacts Cache
        run: echo "Cleaning artifacts..."
        shell: bash
