name: Deploy Production

on:
  push:
    branches: [ main ]

jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Deploy Production Server
      run: echo "Deploying to production server..."
      shell: bash
